FROM node:12.14.0 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build:bff -- --output-path=./dist/out

FROM node:12
RUN npm install -g nodemon
ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN mkdir -p /app/bff && cp -a /tmp/node_modules /app/bff/

WORKDIR /app/bff
COPY --from=build-stage /app/dist/out /app/bff

EXPOSE 3333

CMD [ "nodemon", "main.js" ]
