# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:12.14.0 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build:indocker

FROM nginx:mainline-alpine
COPY --from=build-stage /app/dist/out/ /var/www/html
RUN ls -al /var/www/html
COPY ./nginx-conf-http/nginx.conf /etc/nginx/conf.d/default.conf


